#!/usr/bin/env python3
"""
update_hashes.py — оновлює SHA-256 у manifest.json для всіх файлів.

Використання:
    python update_hashes.py               # тільки хеші
    python update_hashes.py --patch       # хеші + bump patch (0.2.2 → 0.2.3)
    python update_hashes.py --minor       # хеші + bump minor (0.2.2 → 0.3.0)
    python update_hashes.py --major       # хеші + bump major (0.2.2 → 1.0.0)
    python update_hashes.py --install-hook  # встановити pre-commit hook
"""

import sys
import os
import json
import hashlib
import stat
import shutil

# Windows cmd/PowerShell може мати cp1251 — перемикаємо на utf-8
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

MANIFEST_PATH = os.path.join(os.path.dirname(__file__), "manifest.json")
HOOK_PATH = os.path.join(os.path.dirname(__file__), ".git", "hooks", "pre-commit")
SCRIPT_PATH = os.path.abspath(__file__)


# ───────────────────────────── core logic ────────────────────────────────────

def compute_sha256(path: str) -> str | None:
    try:
        with open(path, "rb") as f:
            return hashlib.sha256(f.read()).hexdigest()
    except FileNotFoundError:
        return None


def bump_version(version: str, part: str) -> str:
    major, minor, patch = map(int, version.split("."))
    if part == "major":
        return f"{major + 1}.0.0"
    if part == "minor":
        return f"{major}.{minor + 1}.0"
    return f"{major}.{minor}.{patch + 1}"


def update_manifest(bump: str | None = None) -> bool:
    with open(MANIFEST_PATH, "r", encoding="utf-8") as f:
        manifest = json.load(f)

    base_dir = os.path.dirname(MANIFEST_PATH)
    changed = []
    missing = []

    for entry in manifest["files"]:
        path = os.path.join(base_dir, entry["path"])
        new_hash = compute_sha256(path)

        if new_hash is None:
            missing.append(entry["path"])
            continue

        old_hash = entry.get("sha256", "")
        if new_hash != old_hash:
            changed.append((entry["path"], old_hash[:12] or "none", new_hash[:12]))
            entry["sha256"] = new_hash

    old_version = manifest.get("version", "0.0.0")
    if bump:
        manifest["version"] = bump_version(old_version, bump)

    with open(MANIFEST_PATH, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)
        f.write("\n")

    # ── звіт ──
    if changed:
        print(f"✓ manifest.json updated ({len(changed)} file(s) changed):")
        for path, old, new in changed:
            print(f"  {path}: {old}… → {new}…")
    else:
        print("✓ manifest.json — all hashes up to date, no changes.")

    if missing:
        print(f"\n⚠ Files not found locally (will be created by updater):")
        for p in missing:
            print(f"  {p}")

    if bump:
        print(f"\n↑ Version bumped: {old_version} → {manifest['version']}")

    return bool(changed or bump)


# ─────────────────────────── hook installer ──────────────────────────────────

HOOK_SCRIPT = """\
#!/bin/sh
# Auto-generated by update_hashes.py --install-hook
# Runs before every commit: recomputes SHA-256 and re-stages manifest.json

python "{script}" || exit 1
git add manifest.json
"""


def install_hook():
    hooks_dir = os.path.dirname(HOOK_PATH)
    if not os.path.isdir(hooks_dir):
        print("❌ .git/hooks/ not found — are you in a git repo?")
        sys.exit(1)

    content = HOOK_SCRIPT.format(script=SCRIPT_PATH.replace("\\", "/"))
    with open(HOOK_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)

    # зробити hook виконуваним (потрібно для Git на Windows теж)
    st = os.stat(HOOK_PATH)
    os.chmod(HOOK_PATH, st.st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    print(f"✓ Pre-commit hook installed: {HOOK_PATH}")
    print("  Хеші будуть оновлюватись автоматично перед кожним commit.")


# ──────────────────────────────── main ───────────────────────────────────────

def main():
    args = sys.argv[1:]

    if "--install-hook" in args:
        install_hook()
        return

    bump = None
    for flag in ("--patch", "--minor", "--major"):
        if flag in args:
            bump = flag.lstrip("-")
            break

    update_manifest(bump)


if __name__ == "__main__":
    main()
